# fix: no-op for workflow path trigger (solana release asset URL) — 2026-09-06
[toolchain]
solana_version = "4.2.2"

[features]
seeds = false
skip-lint = false

[programs.devnet]
bonding_curve = "3MQL5zPvAZvC8ZWkLc5qkGy3Cy31KFwxA8zngNQfoTu6"

[programs.mainnet]
bonding_curve = "3MQL5zPvAZvC8ZWkLc5qkGy3Cy31KFwxA8zngNQfoTu6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
