allowBuilds:
  '@reown/appkit': true
  '@stellar/stellar-sdk': true
  bigint-buffer: true
  blake-hash: true
  bufferutil: true
  esbuild: true
  protobufjs: true
  sharp: true
  tiny-secp256k1: true
  unrs-resolver: true
  usb: true
  utf-8-validate: true
  workerd: true
onlyBuiltDependencies:
  - esbuild
  - workerd
  - sharp
  - unrs-resolver
  - bufferutil
  - utf-8-validate
  - bigint-buffer
  - blake-hash
  - protobufjs
  - tiny-secp256k1
  - usb
  - '@reown/appkit'
  - '@stellar/stellar-sdk'